on:
  push:
    branches:
      - main
    paths:
      - ".github/workflows/deploy.yml"
      - ".neko-ssg/**"
      - "src/**"
      - "static/**"

jobs:
  test:
    runs-on: ubuntu-latest
    name: deploy2nekoweb
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install dependencies
        run: yarn ci

      - name: Prepare build
        run: yarn build

      - name: deploy2nekoweb
        uses: indiefellas/deploy2nekoweb@main
        with:
          nekoweb-api-key: ${{ secrets.NEKOWEB_API_KEY }}
          nekoweb-cookie: ${{ secrets.NEKOWEB_COOKIE }}
          nekoweb-domain: "gvfsashgawt.zip"
          nekoweb-username: "gvfsashgawt"
          directory: "build"
